#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armUp,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armRotate,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw1,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           claw2,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int driveToggle = 1;

void closeClaw () {

	if(vexRT[Btn6U] == 1) {
		motor[claw1] -= 40;
		motor[claw2] -= 5;
	}

}

void openClaw () {

	if(vexRT[Btn6D] == 1) {
		motor[claw1] += 40;
		motor[claw2] += 40;
	}

}

bool checkRotation (int sensor) {

	if (sensor == 1) {

		wait1Msec(50);
		if (sensor == 1) {

			return true;

		}

		} else {

		return false;

	}

}

void toggle () {
	
	driveToggle = -driveToggle;

};

task main(){

	int rotations = 0;
	//int driveToggle = 1;

	while (true) {

		if (vexRT[Btn5U] == 1) {
			//toggle();
			driveToggle = -driveToggle;
			//wait1Msec(60);
		}

		//drive
		if (driveToggle == 1) {

			motor[rightMotor] = vexRT[Ch2];
			motor[leftMotor] = vexRT[Ch3];

		} else if (driveToggle == -1) {

			motor[leftMotor]=vexRT[Ch3]+vexRT[Ch4];
    	motor[rightMotor]=vexRT[Ch3]-vexRT[Ch4];

		}

		//arm

		motor[armUp] = (vexRT[Btn5U]*50);
		motor[armUp] = (vexRT[Btn5D] * -50);

		motor[armRotate] = (vexRT[Btn5U] * 50);
		motor[armRotate] = (vexRT[Btn5D] * -50);

		//claw
		closeClaw();
		openClaw();

		//tachometer
		if(checkRotation(1) == true){

			rotations += 1;

		};

	}
}
