#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armUp,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armRotate,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw1,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           claw2,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void toggle (bool toggle) {

	toggle = -toggle;
	wait1Msec(60);

}

void servoControl(tMotor servo, int val) {
		motor[servo] = val;
}

task main(){

	bool driveToggle = true;
	bool armToggle = true;

	while (true) {

		if (vexRT[Btn5U] == 1) {
			driveToggle = true;
		}
		if (vexRT[Btn5D] == 1) {
			driveToggle = false;
		}
		if (vexRT[Btn6U] == 1) {
			armToggle = true;
		}
		if (vexRT[Btn6D] == 1) {
			armToggle = false;
		}

		if(vexRT[Btn7U] == 1) {
			servoControl(claw1, 128);
		}; if( vexRT[Btn7R] == 1) {
			servoControl(claw1, -127);
		}

		if(vexRT[Btn7l] == 1) {
			servoControl(claw2, 128);
		}; if( vexRT[Btn7D] == 1) {
		servoControl(claw2, -127);
		}

		//drive
		if (driveToggle && armToggle) {

			motor[rightMotor] = vexRT[Ch2];
			motor[leftMotor] = vexRT[Ch3];

		} else if (!driveToggle && armToggle) {

			motor[leftMotor]=vexRT[Ch3]+vexRT[Ch4];
    	motor[rightMotor]=vexRT[Ch3]-vexRT[Ch4];

		}

		//arm

		if(!armToggle) {
		motor[armUp] = vexRT[Ch2];
	  }


	}
}
